using System.Security.Claims;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
using AuraApp.Data; using AuraApp.Models;
namespace AuraApp.Controllers;
[ApiController,Route("api/resale")]
public class ResaleController:ControllerBase
{
 private readonly AuraDbContext db; public ResaleController(AuraDbContext c)=>db=c;
 private int Id=>int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
 [HttpGet] public async Task<IActionResult> Listings()=>Ok(await db.ResaleListings.Include(l=>l.Ticket!).ThenInclude(t=>t!.Event).Where(l=>l.Status=="Active"&&l.Ticket!.Status=="Listed").Select(l=>new{l.Id,l.AskingPrice,l.CreatedAt,ticketId=l.Ticket!.TicketCode,eventName=l.Ticket.Event!.Title,eventDate=l.Ticket.Event.EventDate,venue=l.Ticket.Event.Venue,imageUrl=l.Ticket.Event.ImageUrl}).ToListAsync());
 public record ListDto(string TicketCode,decimal AskingPrice);
 [HttpPost("list"),Authorize] public async Task<IActionResult> List(ListDto dto){var u=await db.Users.FindAsync(Id);if(u==null)return Unauthorized();if(!u.IsSubscribed||u.SubscriptionExpiresAt<=DateTime.UtcNow)return StatusCode(403,new{message="An active AURA subscription is required to list tickets."});if(dto.AskingPrice<=0)return BadRequest(new{message="Enter a positive asking price."});var t=await db.Tickets.FirstOrDefaultAsync(x=>x.TicketCode==dto.TicketCode&&x.OwnerUserId==Id);if(t==null)return NotFound(new{message="Ticket not found in your account."});if(t.Status!="Valid")return Conflict(new{message="Only active, unused tickets can be listed."});t.Status="Listed";db.ResaleListings.Add(new ResaleListing{TicketId=t.Id,SellerUserId=Id,AskingPrice=dto.AskingPrice});await db.SaveChangesAsync();return Ok(new{message="Ticket listed for resale.",ticketCode=t.TicketCode});}
 [HttpPost("{listingId:int}/cancel"),Authorize] public async Task<IActionResult> Cancel(int listingId){await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var l=await db.ResaleListings.Include(x=>x.Ticket).FirstOrDefaultAsync(x=>x.Id==listingId&&x.SellerUserId==Id&&x.Status=="Active");if(l==null)return NotFound();var closed=await db.ResaleListings.Where(x=>x.Id==listingId&&x.SellerUserId==Id&&x.Status=="Active").ExecuteUpdateAsync(s=>s.SetProperty(x=>x.Status,"Cancelled"));var restored=await db.Tickets.Where(x=>x.Id==l.TicketId&&x.OwnerUserId==Id&&x.Status=="Listed").ExecuteUpdateAsync(s=>s.SetProperty(x=>x.Status,"Valid"));if(closed==0||restored==0)return Conflict(new{message="Listing changed before it could be cancelled."});await tx.CommitAsync();return Ok(new{message="Listing cancelled."});}
 [HttpPost("{listingId:int}/buy"),Authorize] public async Task<IActionResult> Buy(int listingId){await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var l=await db.ResaleListings.Include(x=>x.Ticket).FirstOrDefaultAsync(x=>x.Id==listingId&&x.Status=="Active");if(l==null||l.Ticket?.Status!="Listed")return NotFound(new{message="This listing is no longer available."});if(l.SellerUserId==Id)return BadRequest(new{message="You cannot buy your own listing."});var buyer=await db.Users.FindAsync(Id);if(buyer==null)return Unauthorized();var seller=l.Ticket.OwnerUserId;var claimed=await db.ResaleListings.Where(x=>x.Id==listingId&&x.Status=="Active").ExecuteUpdateAsync(s=>s.SetProperty(x=>x.Status,"Sold"));var moved=await db.Tickets.Where(x=>x.Id==l.TicketId&&x.OwnerUserId==seller&&x.Status=="Listed").ExecuteUpdateAsync(s=>s.SetProperty(x=>x.OwnerUserId,Id).SetProperty(x=>x.Status,"Valid"));if(claimed==0||moved==0)return Conflict(new{message="This ticket was transferred by another buyer."});db.TicketTransfers.Add(new TicketTransfer{TicketId=l.TicketId,FromUserId=seller,ToUserId=Id,Price=l.AskingPrice});await db.SaveChangesAsync();await tx.CommitAsync();return Ok(new{message="Ticket ownership transferred.",ticketId=l.Ticket.TicketCode,newOwner=buyer.FullName,price=l.AskingPrice});}
 [HttpGet("mine"),Authorize] public async Task<IActionResult> Mine()=>Ok(await db.ResaleListings.Where(l=>l.SellerUserId==Id).OrderByDescending(l=>l.CreatedAt).Select(l=>new{id=l.Id,l.AskingPrice,l.Status,l.CreatedAt,ticket=l.Ticket==null?null:new{l.Ticket.TicketCode,l.Ticket.Status,@event=l.Ticket.Event==null?null:new{l.Ticket.Event.Title,l.Ticket.Event.EventDate,l.Ticket.Event.Venue}}}).ToListAsync());
}

